title: Imanel's Blog
description: ''

url: https://blog.imanel.org
baseurl: /
permalink: pretty
paginate: 10
paginate_path: /page/:num/

plugins:
  - jekyll-feed
  - jekyll-pagination
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Bernard Potocki
  picture: https://gravatar.com/avatar/00c5bb4f96b1094aec27674a810caae6.jpeg
  linkedin: bernardpotocki
  twitter: _imanel

google_analytics: 'UA-19412035-3'
